In [1]:
import pickle
from tqdm import tqdm
import pandas as pd

import seaborn as sns
sns.set()
from matplotlib import pyplot as plt

# WMT data

In [2]:
wmt16 = pickle.load(open('/nas/home/jwei/robust-metrics/wmt16-19-metrics-shared-task/data/pickles/wmt16-sys_level-agg.pkl', 'rb'))
wmt16['year'] = len(wmt16)*[2016]

wmt17 = pickle.load(open('/nas/home/jwei/robust-metrics/wmt16-19-metrics-shared-task/data/pickles/wmt17-sys_level-agg.pkl', 'rb'))
wmt17['year'] = len(wmt17)*[2017]

wmt18 = pickle.load(open('/nas/home/jwei/robust-metrics/wmt16-19-metrics-shared-task/data/pickles/wmt18-sys_level-agg.pkl', 'rb'))
wmt18['year'] = len(wmt18)*[2018]

wmt19 = pickle.load(open('/nas/home/jwei/robust-metrics/wmt16-19-metrics-shared-task/data/pickles/wmt19-sys_level-agg.pkl', 'rb'))
wmt19['year'] = len(wmt19)*[2019]

wmt_mst = pd.concat([wmt16, wmt17, wmt18, wmt19])

In [3]:
wmt16 = pickle.load(open('/nas/home/jwei/robust-metrics/wmt16-19-metrics-shared-task/data/pickles/wmt16-sys_level-all.pkl', 'rb'))
wmt16['year'] = len(wmt16)*[2016]

wmt17 = pickle.load(open('/nas/home/jwei/robust-metrics/wmt16-19-metrics-shared-task/data/pickles/wmt17-sys_level-all.pkl', 'rb'))
wmt17['year'] = len(wmt17)*[2017]

wmt18 = pickle.load(open('/nas/home/jwei/robust-metrics/wmt16-19-metrics-shared-task/data/pickles/wmt18-sys_level-all.pkl', 'rb'))
wmt18['year'] = len(wmt18)*[2018]

wmt19 = pickle.load(open('/nas/home/jwei/robust-metrics/wmt16-19-metrics-shared-task/data/pickles/wmt19-sys_level-all.pkl', 'rb'))
wmt19['year'] = len(wmt19)*[2019]

wmt_mst_all = pd.concat([wmt16, wmt17, wmt18, wmt19])

In [4]:
wmt_toen = wmt_mst_all[wmt_mst_all.lp.str.endswith('en') & ~wmt_mst_all.output.isna()].copy()
wmt_toen.head(1)

,system,sid,raw_score,score,N,lp,reference,source,output,year,system_full
0,online-B,1673,63.0,-0.00167,2,cs-en,Ten statements by Albert Einstein that enriche...,"Desatero výroků Alberta Einsteina, které oboha...",Ten Commandments statements of Albert Einstein...,2016,NaN

### Data validation

In [8]:
wmt_toen.groupby(['lp','year','system']).mean()

                                   sid  raw_score     score         N
lp    year system
cs-en 2016 PJATK           1489.931818  68.954545 -0.024469  1.140828
           cu-mergedtrees  1507.648748  55.783751 -0.502992  1.142388
           jhu-pbmt        1508.147204  72.568873  0.101488  1.137747
           online-A        1496.780488  69.455488  0.000170  1.144715
           online-B        1494.782538  70.844961  0.050822  1.139535
...                                ...        ...       ...       ...
zh-en 2018 online-B.0      2009.829935  77.667910  0.111083  1.162108
           online-F.0      2000.536160  64.429426 -0.376822  1.159601
           online-G.0      1987.291956  65.927673 -0.326750  1.155909
           online-Y.0      1987.352278  74.963090 -0.005269  1.148947
           uedin.5652      1988.530663  74.527778 -0.017266  1.152324

[246 rows x 4 columns]

In [9]:
wmt_mst[(wmt_mst.year == 2018) & (wmt_mst.lp == 'zh-en')]

,lp,system,BLEU,NIST,CDER,PER,WER,TER,score,raw_score,year
19,zh-en,NiuTrans.5740,0.3077,8.0277,0.4853,0.6168,0.3805,0.4156,0.140,78.824465,2018
20,zh-en,online-B.0,0.3125,8.1662,0.4910,0.6223,0.3985,0.4330,0.111,77.667910,2018
21,zh-en,UCAM.5586,0.2982,8.0474,0.4797,0.6105,0.3814,0.4177,0.109,77.899041,2018
22,zh-en,Unisound.5712,0.3075,8.2187,0.4872,0.6153,0.3919,0.4289,0.108,78.043637,2018
23,zh-en,Tencent-ensemble-system.5742,0.3150,8.2082,0.4957,0.6253,0.3958,0.4314,0.099,77.455919,2018
24,zh-en,Unisound.5668,0.3005,8.2139,0.4824,0.6060,0.3975,0.4340,0.094,77.506582,2018
25,zh-en,Li-Muze.5736,0.2945,8.0500,0.4753,0.6027,0.3796,0.4161,0.091,77.921977,2018
26,zh-en,NICT.5539,0.2867,7.8559,0.4693,0.5985,0.3698,0.4043,0.089,77.043952,2018
27,zh-en,UMD.5681,0.2630,7.6530,0.4498,0.5783,0.3620,0.3973,0.078,76.746277,2018
28,zh-en,online-Y.0,0.2643,7.5644,0.4542,0.5854,0.3617,0.3954,-0.005,74.963090,2018
29,zh-en,uedin.5652,0.2597,7.5425,0.4452,0.5577,0.3683,0.3998,-0.017,74.527778,2018
30,zh-en,online-A.0,0.2404,7.3964,0.4268,0.5667,0.3418,0.3787,-0.061,73.569270,2018
31,zh-en,online-G.0,0.1697,6.3451,0.3477,0.5371,0.2206,0.2675,-0.327,65.927673,2018
32,zh-en,online-F.0,0.1198,5.3354,0.3015,0.4749,0.1926,0.2290,-0.377,64.429426,2018

# Scoring

In [10]:
print(len(wmt_toen))

476073

In [11]:
outputs = wmt_toen['output'].tolist()
references = wmt_toen['reference'].tolist()

In [12]:
fh = open('./outputs', 'wt')
[ fh.write(str(i).strip() + '\n') for i in outputs ]
fh.close()

fh = open('./references', 'wt')
[ fh.write(str(i).strip() + '\n') for i in references ]
fh.close()

In [ ]:
!CUDA_VISIBLE_DEVICES=0 python run_bert_score.py

In [13]:
scores = [ float(i) for i in open('./scores', 'rt') ]
wmt_toen['bert_score'] = scores

In [15]:
pickle.dump(wmt_toen, open('../pickles/wmt19_toen_bert_score.pkl', 'wb'))